[tox]
envlist = py311, lint, mypy
isolated_build = true

[testenv]
extras = dev
commands = pytest {posargs}

[testenv:lint]
extras = dev
commands =
  ruff check .
  ruff format --check feature_flags tests

[testenv:mypy]
extras = dev
commands = mypy feature_flags
